### ISSUE TITLE
Consider add a readme with reference to your blog post

### ISSUE THREAD

**Issue by CaledoniaProject** [ohjeongwook/PowerShellRunBox#2]
Can you create a README file and add reference to this blog post?
https://blog.apnic.net/2019/10/23/powershellrunbox-analyzing-powershell-threats-using-powershell-debugging/

**Comment by ohjeongwook** [comment]
Fixed with https://github.com/ohjeongwook/PowerShellRunBox/commit/0ac67b2db1b4645461bff41617700e63fbffba7b.
